### ISSUE TITLE
Consider accepting Ethical Open Source licensed projects 

### ISSUE THREAD

**Issue by Alch-Emi** [humanetech-community/awesome-humane-tech#59]
The current CONTRIBUTING.md bars the admission of software projects without a FSF approved license, yet many ethical software projects may seek to use [ethical licenses](https://ethicalsource.dev/licenses/), which the FSF refuses to acknowledge, but nevertheless are open source licenses that grant distribution and modification rights to users.

It is undeniable that these licenses align with the objectives of so much of the software featured by this project, and I'd strongly recommend allowing EOS licenses in the project.

The Ethical Source Movement collective currently curates a list of approved EOS licenses [on their website](https://ethicalsource.dev/licenses/).

See also: #58

**Comment by aschrijver** [comment]
Thank you for PR'ing. #58 has been merged :)

**Comment by Alch-Emi** [comment]
Sorry for the confusion, but I was actually referring to the second bullet of the `CONTRIBUTING.md` file, which #58 did not make an attempt to change.  The `CONTRIBUTING.md` file requires that *future* submissions be FSF approved, which would bar any EOS projects from admission.  This issue is meant to suggest a change to this rule.  Is that something you might consider?

**Comment by aschrijver** [comment]
Ah, I am sorry, I misunderstood.

Tbh, I will keep things as they are now. I am sympathetic to the efforts and ideas of ethical licenses, and have also brought up some discussion topics on our forum. I am also aware of the raging debates surrounding the topic and the controversy. This is something I don't want to bring to this list.

But I find it important that there is a reference in the Ethics section for people to inform themselves about the subject. Since inclusion I already got pinged by people questioning that. For those I'll gladly explain that they are free to make their own choice, but that further discussion should be at the appropriate location, not on this list.

**Comment by Alch-Emi** [comment]
I can't believe you're already getting backlash, and I'm really sorry to hear.  I understand and absolutely respect not wanting to draw the ire of the hippocratic hate crowd.  It's my personal opinion that the the conflict between the rights of users and the rights of those potentially oppressed by users is an unavoidable discussion for any space discussing software ethics, but I'd never ask anyone to put themselves in harms way for what would mostly be a symbolic gesture.  If someone does approach you with an EOS listing, I would of course *strongly* encourage you to reconsider at that point, but if for now you want to avoid that discussion and all the mess that comes with it for now, I completely understand.

Thank you very much for including the license itself on the project's page, and I appreciate everything you're doing to support ethical tech!

**Comment by aschrijver** [comment]
Thank you. That appreciation extends to you from my end too :)
