### ISSUE TITLE
www.haveibeenpowned.com

### ISSUE THREAD

**Issue by schklom** [humanetech-community/awesome-humane-tech#62]
In Security, you definitely want to add this awesome website.
It contains lists of email addresses and (hashed) passwords from most if not all the recent data breaches.
You can check if your email has appeared in a breach very easily and quickly. If paranoid, you can also download the (I remember 2GB) list of leaked emails and hashed passwords and check offline.

**Comment by aschrijver** [comment]
Thank you for the suggestion @schklom 

I am familiar with the site, and I think the service is also integrated with Firefox. I agree it is an awesome website. But it is not an open-source project, rather than a Troy Hunt personal thing (and he's sponsored by 1Password). Hence it is not a good fit for this list. Also - though we had some security-related resources - given the vastness of the field and the special expertise that is involved we are not collecting security-related entries at all, but rather point to the respective awesome list for that.
